### PR TITLE
[RTM] Associate comments with members

### PR DESCRIPTION
**Pull request by m-vo**
This PR adds a field `member` to `tl_comments` which receives the logged in member's id when a comment is stored (or null if the users is a guest).

see #5 

I did not add anything to the templates for BC reasons (and: old comments would have the member id 0 set and need some manual migration) nor did I add it explicitly to the template's vars. So this is kind of a hidden feature but would at least allow something like the following in a custom version of the `com_default` template:

```php
$member = \MemberModel::findById($this->arrData['member']);
if($member) { echo $member->...; }
```

This allows for several things like displaying user avatars or additional info in comments, listing comments in a user dashboard and so on.

---

Remarks: 
* I don't like the name `member`. This field links the *actual author* of the comment and should imo be called something like `author` or `authorProfile` but this term is already used for the author of the reply.
* Note that the data stored within a comment (email, name, ..) could differ from the one in the member profile.

### CODE REVIEW

**Comment by daebak74** [comment]
I think not need to add other field just use author because if is a reply the field addReply is true else is false. So just need to add in Comments.php the logged user id to author field.

**Comment by leofeyer** [comment]
As discussed in Mumble on October 18th, `member` is ok as column name.

**Comment by m-vo** [comment]
As discussed on mumble the member now gets displayed in the backend if available:

screenshot_20181027_212117

(We could also add the information in the `tl_comment` label callback, but it's is already a lot in there and a duplicate author/member could be confusing.)

@leofeyer Anything else to add/modify?

**Comment by leofeyer** [comment]
Is there really a use-case in which a comment needs to be re-assigned from one member to another? I don't think the field needs to be in the back end form.

**Comment by m-vo** [comment]
Probably not, but there could be the use-case to assign comments that have been made without the member field present (<4.7) or that were issued without login to a member later on.

**Comment by leofeyer** [comment]
Merged in contao/contao@e8002e0767d2d7ecc4f71ee2e323d5705dc0b8e4.

**Pull request closed without merging**
